### ISSUE TITLE
Error in qqnorm.default(plotDatalnfluence): y is empty or has only NAs

### ISSUE THREAD

**Issue by Christianhigton** [kylehamilton/MAJOR#7]
Hello, I have side loaded MAJOR_1.0.2-win64-R3.4.1.jmo and I am using the correlation coefficients dialogue box, however when I enter the variables as per the screen shot I get an error. Apologies if this is an error between keyboard and chair. Many thanks, Chris

![dialogue box](https://user-images.githubusercontent.com/6468080/71972075-e070c900-3203-11ea-81c1-9a2ee59e3dc2.png)
![data](https://user-images.githubusercontent.com/6468080/71972116-f4b4c600-3203-11ea-99bb-c5925f8ed70a.png)

P.S thank you for creating such a useful add on for Jamovi

**Comment by kylehamilton** [comment]
Hey @Christianhigton nope you're 100% correct this is an error and it's my complete fault. What happened is I upload a half complete version to GitHub because I was busy and had to do work on my candidacy paper. I didn't think anyone would be using the development version, in the future, I'll make sure to use the branches on GitHub so I can prevent this from happening again. I'm glad I left this very helpful note in the commit "Not stable at this time but good enough for right now.". 
https://github.com/kylehamilton/MAJOR/commit/f6e3d1d16ee4a99f50c4797295a1a447253ea2c5

Again super sorry, try using the development version from a previous commit and let me know if it works for you. I'm at a writing retreat but I'll check my email every couple hours so feel free to reach out if there are any other problems.


https://github.com/kylehamilton/MAJOR/blob/30f3926dcd7aa895de204b9a6b84e38ed9e0969e/MAJOR_1.0.2-win64-R3.4.1.jmo

**Comment by Christianhigton** [comment]
Thanks for taking the time to get back to me. I have tested the previous version and works well. Thank you for taking the time to reply and thank you for creating such a useful piece of software.  I hope the writing retreat went well.

**Comment by kylehamilton** [comment]
Glad everything is working, if you have any other questions just let me know. Excited to see your work come out!
